[package]
name = "indexed_db_futures"
version = "0.2.0"
authors = ["Arturas Molcanovas <amolc@protonmail.com>"]
edition = "2018"
license = "MIT"
description = "Future bindings for IndexedDB via web_sys"
repository = "https://github.com/Alorel/rust-indexed-db"
keywords = ["wasm", "indexeddb", "future", "webassembly", "idb"]
categories = ["asynchronous", "database", "wasm", "web-programming"]
include = [
    "src/",
    "Cargo.toml",
    "README.md"
]

[features]
default = [
    "cursors",
    "indices"
]
cursors = [
    "web-sys/IdbCursor",
    "web-sys/IdbCursorWithValue",
    "web-sys/IdbCursorDirection"
]
indices = [
    "web-sys/IdbIndex",
    "web-sys/IdbIndexParameters"
]
nightly = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.28"

[dependencies]
cfg-if = "1.0.0"
js-sys = "0.3.55"
uuid = {version = "0.8.2", features = ["v4", "wasm-bindgen"]}
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"

[dependencies.web-sys]
version = "0.3.55"
features = [
    "DomException",
    "DomStringList",
    "Event",
    "EventTarget",
    "IdbDatabase",
    "IdbFactory",
    "IdbObjectStore",
    "IdbObjectStoreParameters",
    "IdbOpenDbRequest",
    "IdbKeyRange",
    "IdbRequest",
    "IdbRequestReadyState",
    "IdbTransaction",
    "IdbTransactionMode",
    "IdbVersionChangeEvent",
    "Window"
]
