name: Release
concurrency: release
on:
  push:
    branches:
      - release

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: --deny warnings

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yml

  release:
    name: Release
    needs:
      - test
    runs-on: ubuntu-latest
    environment: crates-io
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Parse
        id: parse
        uses: alorel-actions/semantic-release-lite@v0
        with:
          stay-at-zero: true
          minor-types: |
            feat: Features
          patch-types: |
            fix: Bug Fixes
          trivial-types: |
            chore: Maintenance
            deps: Dependency updates
            ci: CI & Build
            build: CI & Build
            refactor: Refactors
            docs: Documentation
            perf: Performance

      - name: Prep release
        if: ${{ steps.parse.outputs.should-release }}
        id: prep
        uses: ./.github/actions/prep-release
        with:
          release-type: ${{ steps.parse.outputs.release-type }}
          version: ${{ steps.parse.outputs.next-version }}

      - name: Release
        if: ${{ steps.prep.outputs.in-sync }}
        uses: ./.github/actions/release
        with:
          version: ${{ steps.parse.outputs.next-version }}
          changelog: ${{ steps.parse.outputs.changelog }}
          issues-closed: ${{ steps.parse.outputs.issues-closed }}
          crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
